defaults: &defaults

  geo_service_providers:
    default: ipstack

    ipstack:
      api_url: "https://api.ipstack.com/%s?access_key=%s"
      api_access_key: "9a512cc46d662d6aa840d0fc1123ba3a"
      adapter: IpstackAdapter

development:
  <<: *defaults

test:
  <<: *defaults
  
production:
  <<: *defaults


